### ISSUE TITLE
Cannot generate on Mac 

### ISSUE THREAD

**Issue by Boerrild** [vlingo/vlingo-xoom-starter#24] opened 2021-02-25 21:44 UTC
When I push the final Generate-button I get an error. Well hidden in stack traces in the console, I realise that the "mvnw"-tool is missing execution permission. Maybe add a note to the README to also run 

    chmod 755 resources/archetypes/mvnw

in addition to 

    chmod 775 xoom

**Comment by VaughnVernon** [comment] 2021-02-25 21:50
@Boerrild Thanks for reporting. Sorry. We should be able to set rwx for the user level.

@danilo-ambrosio Please support ASAP.
https://www.journaldev.com/855/java-set-file-permissions-posixfilepermission

The following shows 777 but I think it would be 744 and allow the owner to change it to higher because it might fail if the installation directory is not owned by the installing user.

```
        //using PosixFilePermission to set file permissions 777
        Set<PosixFilePermission> perms = new HashSet<PosixFilePermission>();
        //add owners permission
        perms.add(PosixFilePermission.OWNER_READ);
        perms.add(PosixFilePermission.OWNER_WRITE);
        perms.add(PosixFilePermission.OWNER_EXECUTE);
        //add group permissions
        perms.add(PosixFilePermission.GROUP_READ); 
        perms.add(PosixFilePermission.GROUP_WRITE);
        perms.add(PosixFilePermission.GROUP_EXECUTE);
        //add others permissions
        perms.add(PosixFilePermission.OTHERS_READ);
        perms.add(PosixFilePermission.OTHERS_WRITE);
        perms.add(PosixFilePermission.OTHERS_EXECUTE);
        
        Files.setPosixFilePermissions(Paths.get("/path-to-mvnw/mvnw"), perms);
```

**Comment by VaughnVernon** [comment] 2021-02-25 23:51
Fixed by https://github.com/vlingo/vlingo-xoom-starter/commit/b153a0b259ebc7d8ebb8f00f7f8572c55e2f2153

**Closed by VaughnVernon** 2021-02-25 23:51 UTC

**Comment by VaughnVernon** [comment] 2021-02-26 21:36
@Boerrild I have confirmed this fix on MBP + MacOS.
